name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Frontend and Backend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      ### 🔹 Backend
      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Setup SQLite test database
        run: node setupTestDB.js
        working-directory: backend

      - name: Run backend tests
        run: npm test
        working-directory: backend

      ### 🔹 Frontend
      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Run frontend tests
        run: npm test
        working-directory: frontend
